### ISSUE TITLE
Update watch state in trakt.tv

### ISSUE THREAD

**Issue by Norien** [caphm/kodi-service.strmfilemarker#1]
Would love for this service to mark strm files as watched in the trakt addon.

**Comment by caphm** [comment]
The trakt addon should already correctly identify playing library items based on strm files, as long as their metadata is somehow accessible.

Triggering the trakt addon from within this service is not possible. Trakt is using an internal dispatch queue to trigger actions like marking as watched and since it does not expose any callable endpoints, there's no way for other addons to trigger these actions.

It can be achieved by adding my logic for determining the currently playing item to the trakt addon (method traktPlayer.onPlayBackStarted() in service.py). I will not open a PR for this though, as my matching logic is way more fragile than theirs.

On another note, I might draw some inspiration on their code to improve item matching though, so thanks for the unintended hint ;)
